### ISSUE TITLE
1.28 release always results in SS rank

### ISSUE THREAD

**Issue by McLovin836** [StackDoubleFlow/CustomJSONData#34]
When enabling mod in BMBF and playing any song in BS 1.28, the results screen always shows SS rank, no matter what your score is

**Comment by ImWoood** [comment]
Will this get fixed because I have the exact same problem with this mod and the issue you mentioned was closed without a fix. It would be nice if you could do something about it because I need this mod, without many maps won't work :(

**Comment by Fernthedev** [comment]
Feel free to fix it then.

The issue was closed because it was a duplicate, common practice in GitHub and this is no exception.

**Comment by ImWoood** [comment]
Sry didn't know that. Do you have any idea what could cause this bug?

**Comment by Metalit** [comment]
Forgot to mention in it, but this should be fixed in https://github.com/StackDoubleFlow/CustomJSONData/pull/37

**Comment by Fernthedev** [comment]
Fixed by #37

**Comment by Dozer58** [comment]
Any way to download a qmod with the fixed code?

**Comment by copyrightbreaker** [comment]
Issue still not fixed unfortunately.

**Comment by tomporter518** [comment]
Recently installed Chroma from: [Beat Saber Mod Versions](https://computerelite.github.io/tools/Beat_Saber/questmods.html) on my new Quest 3. Prior to installing, but with a modded Beat Saber, I got various ranks. With Chroma installed even very, very poor performance results in an SS.

**Comment by GitEmulate** [comment]
Still having this issue. Once again asking how to get an updated version of this mod with the fix, since the latest release is so old it's before https://github.com/StackDoubleFlow/CustomJSONData/pull/37

**Comment by kingpanguan** [comment]
same

**Comment by Dozer58** [comment]
Thing is 1.28 has multiplayer mods, the new versions don't, and using the 1.28 mod installer always installed the version of JSONData that doesn't have the fix.

Thanks for the link to the fixed 1.28 qmod, people can now play multiplayer without getting SS

**Comment by maxkoshevoi** [comment]
@Fernthedev I think for Quest 1 (which I have) [it's only possible to mode up to version 1.28](https://bsmg.wiki/quest/modding-quest1.html) unfortunately.. 
Also https://www.questmodding.com/ mentions 1.28 as latest modable version so people with Quest 2 & 3 can stumble upon this issue as well

Thank you for providing fixed qmod file! It seems that it's intended to be installed with Scotland2, but 1.28 mods use QuestLoader, so I'm getting this error while trying to install it (repatching doesn't help since other mods use QuestLoader):
![image](https://github.com/user-attachments/assets/35d68531-6a82-44e4-959b-9b2fb541981d)

Could you please compile 0.19.4 qmod for QuestLoader?

**Comment by Dozer58** [comment]
Does this version I have work with quest loader? https://filebin.net/rybbb3l7c64ciq9g

**Comment by maxkoshevoi** [comment]
> Does this version I have work with quest loader? https://filebin.net/rybbb3l7c64ciq9g

Yes! Thank you!! The score calculates properly now. QuestPatcher says its 0.19.3, but your file is different from the one here https://github.com/StackDoubleFlow/CustomJSONData/releases/tag/v0.19.3
No idea where you got that, but thank you!
